/**
 * Reload must not show a beat of the wrong brand.
 *
 * The `spaces_theme_mode` record in localStorage carries the accent this device
 * picked. The server cannot read it, so the first paint of the stylesheet uses
 * the shipped violet — unless a synchronous bootstrap script in <head> applies
 * the saved tokens before the browser gets a chance to paint. These tests lock
 * the contract: the script exists, is emitted before HeadContent, and covers
 * every palette the settings surface can pick.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { ACCENT_PALETTES, getThemeBootstrapScript, type ThemeAccent } from "@/lib/theme-state";

const src = (rel: string) => readFileSync(new URL(rel, import.meta.url), "utf8");

describe("the theme bootstrap script", () => {
  const script = getThemeBootstrapScript();

  it("is a self-contained IIFE (no imports, no bundler assumptions)", () => {
    expect(script.startsWith("(function(){try{")).toBe(true);
    expect(script.endsWith("}catch(e){}})();")).toBe(true);
    expect(script).not.toMatch(/\bimport\b/);
    expect(script).not.toMatch(/\bexport\b/);
  });

  it("reads the exact key persistTheme writes", () => {
    expect(script).toContain(`var k="spaces_theme_mode";`);
  });

  it("ships every accent the settings surface can select", () => {
    for (const accent of Object.keys(ACCENT_PALETTES) as ThemeAccent[]) {
      // The palette table is inlined; a missing accent would fall through to
      // violet on first paint, which is exactly the flash we are preventing.
      expect(script).toContain(`"${accent}"`);
      const p = ACCENT_PALETTES[accent];
      expect(script).toContain(p.brand);
      expect(script).toContain(p.brandPink);
      expect(script).toContain(p.brandOrange);
      expect(script).toContain(p.brandDark);
      expect(script).toContain(p.brandPinkDark);
      expect(script).toContain(p.brandOrangeDark);
    }
  });

  it("sets --brand and the two derived tokens before any bundle loads", () => {
    expect(script).toContain("r.style.setProperty('--brand'");
    expect(script).toContain("r.style.setProperty('--brand-pink'");
    expect(script).toContain("r.style.setProperty('--brand-orange'");
  });

  it("applies the .dark and .reduce-motion classes so the stylesheet's variants kick in", () => {
    expect(script).toContain("r.classList.add('dark')");
    expect(script).toContain("r.classList.add('reduce-motion')");
  });

  it('re-points the <meta name="theme-color"> so the browser chrome matches too', () => {
    expect(script).toContain('meta[name=\\"theme-color\\"]');
    expect(script).toContain("m.setAttribute('content',H[a])");
  });

  it("wraps localStorage in its own try/catch (private mode must not blank the page)", () => {
    // The outer catch keeps the whole script safe; the inner one is deliberate
    // so a `SecurityError: The operation is insecure` from localStorage does
    // not skip the CSS-variable writes further below.
    expect(script).toMatch(/try\{raw=localStorage\.getItem\(k\);\}catch\(e\)\{\}/);
  });
});

describe("__root.tsx wires the bootstrap into the <head>", () => {
  const root = src("../src/routes/__root.tsx");

  it("renders it as an inline script", () => {
    // Match the raw __html payload rather than the React prop name — the
    // script string itself is generated by `getThemeBootstrapScript()` on
    // the server from static palette literals, never from user data.
    expect(root).toMatch(/__html: getThemeBootstrapScript\(\)/);
  });

  it("runs it before HeadContent so it precedes the stylesheet link", () => {
    const scriptIdx = root.indexOf("getThemeBootstrapScript()");
    const headContentIdx = root.indexOf("<HeadContent");
    expect(scriptIdx).toBeGreaterThan(0);
    expect(headContentIdx).toBeGreaterThan(scriptIdx);
  });

  it('still emits the fallback <meta name="theme-color"> for SSR', () => {
    // The script re-points the tag at runtime; the head still has to declare a
    // sensible default for the crawler / first-byte case where scripts don't run.
    expect(root).toContain('{ name: "theme-color", content: themeColorFor() }');
  });
});
